/* AUTO-GENERATED by pipeline — do not edit */
import type { EventDef } from '../types';
import type { EventStatus } from '../types';
import HIDDEN_EVENTS from './config';
import E_20260324_video from './20260324-video';
import E__no_peaking from './_no-peaking';

export type EventWithStatus = EventDef & { status: EventStatus };

function computeStatus(e: EventDef): EventStatus {
  if (HIDDEN_EVENTS.includes(e.meta.slug)) return 'hidden';
  const now = Date.now();
  const start = new Date(e.meta.start).getTime();
  const end = new Date(e.meta.end).getTime();
  if (now < start) return 'upcoming';
  if (now <= end) return 'ongoing';
  return 'ended';
}

const ALL: EventDef[] = [E_20260324_video, E__no_peaking];

export const EVENTS: EventWithStatus[] = ALL.map(e => ({
  ...e,
  status: computeStatus(e),
}));
