/* AUTO-GENERATED by pipeline — do not edit */
import type { EventDef } from '../types';
import type { EventStatus } from '../types';
import EVENT_STATUS from './config';
import E_20260201_video from './20260201-video';
import E__no_peaking from './_no-peaking';

export type EventWithStatus = EventDef & { status: EventStatus };

const ALL: EventDef[] = [E_20260201_video, E__no_peaking];

export const EVENTS: EventWithStatus[] = ALL.map(e => ({
  ...e,
  status: (EVENT_STATUS[e.meta.slug] ?? 'hidden') as EventStatus,
}));
