// Task definitions for Progress Tracker
// All possible tasks with their configurations

import type { TaskDefinition } from '@/types/progress'

export const DAILY_TASK_DEFINITIONS: Record<string, TaskDefinition> = {
  // Regular tasks
  'free-recruit-custom': {
    id: 'free-recruit-custom',
    type: 'daily',
    category: 'task',
    labelKey: 'progress.task.free-recruit-custom',
    permanent: true,
    maxCount: 1,
  },
  'free-recruit-demiurge': {
    id: 'free-recruit-demiurge',
    type: 'daily',
    category: 'task',
    labelKey: 'progress.task.free-recruit-demiurge',
    permanent: true,
    maxCount: 1,
  },
  'guild-security-area': {
    id: 'guild-security-area',
    type: 'daily',
    category: 'task',
    labelKey: 'progress.task.guild-security-area',
    permanent: true,
    maxCount: 1,
  },
  // Optional/Event tasks (not always available)
  'joint-challenge': {
    id: 'joint-challenge',
    type: 'daily',
    category: 'task',
    labelKey: 'progress.task.joint-challenge',
    permanent: false,
    maxCount: 2,
  },
  'guild-raid': {
    id: 'guild-raid',
    type: 'daily',
    category: 'task',
    labelKey: 'progress.task.guild-raid',
    permanent: false,
    maxCount: 2,
  },
  'world-boss': {
    id: 'world-boss',
    type: 'daily',
    category: 'task',
    labelKey: 'progress.task.world-boss',
    permanent: false,
    maxCount: 1,
  },
  'terminus-isle': {
    id: 'terminus-isle',
    type: 'daily',
    category: 'task',
    labelKey: 'progress.task.terminus-isle',
    permanent: true,
    maxCount: 1, // Can be increased to 2 with support pack
  },
  'bounty-hunter': {
    id: 'bounty-hunter',
    type: 'daily',
    category: 'task',
    labelKey: 'progress.task.bounty-hunter',
    permanent: true,
    maxCount: 3, // Can be increased to 4 with Veronica Premium Pack
  },
  'bandit-chase': {
    id: 'bandit-chase',
    type: 'daily',
    category: 'task',
    labelKey: 'progress.task.bandit-chase',
    permanent: true,
    maxCount: 3, // Can be increased to 4 with Veronica Premium Pack
  },
  'upgrade-stone-retrieval': {
    id: 'upgrade-stone-retrieval',
    type: 'daily',
    category: 'task',
    labelKey: 'progress.task.upgrade-stone-retrieval',
    permanent: true,
    maxCount: 3, // Can be increased to 4 with Veronica Premium Pack
  },
  'defeat-doppelganger': {
    id: 'defeat-doppelganger',
    type: 'daily',
    category: 'task',
    labelKey: 'progress.task.defeat-doppelganger',
    permanent: true,
    maxCount: 10,
  },
  'special-request-ecology': {
    id: 'special-request-ecology',
    type: 'daily',
    category: 'task',
    labelKey: 'progress.task.special-request-ecology',
    permanent: true,
    maxCount: 3,
  },
  'special-request-identification': {
    id: 'special-request-identification',
    type: 'daily',
    category: 'task',
    labelKey: 'progress.task.special-request-identification',
    permanent: true,
    maxCount: 3,
  },
  'memorial-match': {
    id: 'memorial-match',
    type: 'daily',
    category: 'task',
    labelKey: 'progress.task.memorial-match',
    permanent: true,
    maxCount: 5,
  },
  'story-hard': {
    id: 'story-hard',
    type: 'daily',
    category: 'task',
    labelKey: 'progress.task.story-hard',
    permanent: true,
    maxCount: 30,
  },
  'elemental-tower': {
    id: 'elemental-tower',
    type: 'daily',
    category: 'task',
    labelKey: 'progress.task.elemental-tower',
    permanent: true,
    maxCount: 5,
  },
  'ad-stamina': {
    id: 'ad-stamina',
    type: 'daily',
    category: 'task',
    labelKey: 'progress.task.ad-stamina',
    permanent: true,
    maxCount: 10, // 10 ads × 18 stamina = 180 stamina/day
  },
  // Recurring tasks (special cycle)
  'infinite-corridor': {
    id: 'infinite-corridor',
    type: 'daily',
    category: 'recurring',
    labelKey: 'progress.task.infinite-corridor',
    permanent: true,
    maxCount: 1,
    resetIntervalDays: 3, // Resets every 3 days
  },
  // Premium Shop > Normal > Daily/Weekly/Monthly
  'shop-daily-free-gift': {
    id: 'shop-daily-free-gift',
    type: 'daily',
    category: 'shop',
    labelKey: 'progress.task.shop-daily-free-gift',
    permanent: true,
    maxCount: 1,
    shopCategory: 'progress.shop.premium-shop',
    shopSubcategory: 'progress.shop.normal',
    shopTab: 'progress.shop.daily-weekly-monthly',
  },
  'shop-event-jc-stamina': {
    id: 'shop-event-jc-stamina',
    type: 'daily',
    category: 'shop',
    labelKey: '',
    permanent: true,
    maxCount: 1,
    shopCategory: 'progress.shop.adventurer-shop',
    shopSubcategory: 'progress.shop.event-shop',
    shopTab: 'progress.shop.joint-challenge',
    shopItemKey: 'Stamina',
    shopItemQuantity: 50,
  },
  'shop-fp-stamina': {
    id: 'shop-fp-stamina',
    type: 'daily',
    category: 'shop',
    labelKey: '',
    permanent: true,
    maxCount: 4,
    shopCategory: 'progress.shop.adventurer-shop',
    shopSubcategory: 'progress.shop.friendship-point',
    shopItemKey: 'Stamina',
    shopItemQuantity: 30,
  },
  'shop-fp-gold': {
    id: 'shop-fp-gold',
    type: 'daily',
    category: 'shop',
    labelKey: '',
    permanent: true,
    maxCount: 1,
    shopCategory: 'progress.shop.adventurer-shop',
    shopSubcategory: 'progress.shop.friendship-point',
    shopItemKey: 'Gold',
    shopItemQuantity: 10000,
  },
  'shop-fp-arena-ticket': {
    id: 'shop-fp-arena-ticket',
    type: 'daily',
    category: 'shop',
    labelKey: '',
    permanent: true,
    maxCount: 1,
    shopCategory: 'progress.shop.adventurer-shop',
    shopSubcategory: 'progress.shop.friendship-point',
    shopItemKey: 'Arena Ticket',
    shopItemQuantity: 5,
  },
  // Content > General
  'shop-general-effectium': {
    id: 'shop-general-effectium',
    type: 'daily',
    category: 'shop',
    labelKey: '',
    permanent: true,
    maxCount: 1,
    shopCategory: 'progress.shop.premium-shop',
    shopSubcategory: 'progress.shop.general',
    shopItemKey: 'Effectium',
    shopItemQuantity: 100,
  },
  // Content > Arena Shop
  'shop-arena-stamina': {
    id: 'shop-arena-stamina',
    type: 'daily',
    category: 'shop',
    labelKey: '',
    permanent: true,
    maxCount: 3,
    shopCategory: 'progress.shop.adventurer-shop',
    shopSubcategory: 'progress.shop.arena-shop',
    shopItemKey: 'Stamina',
    shopItemQuantity: 50,
  },
  'shop-arena-gold': {
    id: 'shop-arena-gold',
    type: 'daily',
    category: 'shop',
    labelKey: '',
    permanent: true,
    maxCount: 1,
    shopCategory: 'progress.shop.adventurer-shop',
    shopSubcategory: 'progress.shop.arena-shop',
    shopItemKey: 'Gold',
    shopItemQuantity: 10000,
  },
  'shop-starmem-stamina': {
    id: 'shop-starmem-stamina',
    type: 'daily',
    category: 'shop',
    labelKey: '',
    permanent: true,
    maxCount: 3,
    shopCategory: 'progress.shop.premium-shop',
    shopSubcategory: 'progress.shop.star-memory',
    shopItemKey: 'Stamina',
    shopItemQuantity: 150,
  },
  'shop-starmem-ticket': {
    id: 'shop-starmem-ticket',
    type: 'daily',
    category: 'shop',
    labelKey: '',
    permanent: true,
    maxCount: 1,
    shopCategory: 'progress.shop.premium-shop',
    shopSubcategory: 'progress.shop.star-memory',
    shopItemKey: 'Special Recruitment Ticket (Event)',
    shopItemQuantity: 1,
  },
  'shop-starmem-gold': {
    id: 'shop-starmem-gold',
    type: 'daily',
    category: 'shop',
    labelKey: '',
    permanent: true,
    maxCount: 3,
    shopCategory: 'progress.shop.premium-shop',
    shopSubcategory: 'progress.shop.star-memory',
    shopItemKey: 'Gold',
    shopItemQuantity: 200000,
  },
  'shop-starmem-arena': {
    id: 'shop-starmem-arena',
    type: 'daily',
    category: 'shop',
    labelKey: '',
    permanent: true,
    maxCount: 1,
    shopCategory: 'progress.shop.premium-shop',
    shopSubcategory: 'progress.shop.star-memory',
    shopItemKey: 'Arena Ticket',
    shopItemQuantity: 5,
  },
  'shop-guild-gold': {
    id: 'shop-guild-gold',
    type: 'daily',
    category: 'shop',
    labelKey: '',
    permanent: true,
    maxCount: 5,
    shopCategory: 'progress.shop.guild',
    shopSubcategory: 'progress.shop.guild-shop',
    shopTab: 'progress.shop.daily-products',
    shopItemKey: 'Gold',
    shopItemQuantity: 10000,
  },
}

export const WEEKLY_TASK_DEFINITIONS: Record<string, TaskDefinition> = {
  // Regular tasks
  'arena-battle': {
    id: 'arena-battle',
    type: 'weekly',
    category: 'task',
    labelKey: 'progress.task.arena-battle',
    permanent: true,
    maxCount: 30,
  },
  'monad-gates-exploration': {
    id: 'monad-gates-exploration',
    type: 'weekly',
    category: 'task',
    labelKey: 'progress.task.monad-gates-exploration',
    permanent: true,
    maxCount: 1,
  },
  'adventure-license': {
    id: 'adventure-license',
    type: 'weekly',
    category: 'task',
    labelKey: 'progress.task.adventure-license',
    permanent: true,
    maxCount: 12, // Dynamic: 2/3/4 combats per stage × 3 stages = 6/9/12
  },
  // Premium Shop > Normal > Daily/Weekly/Monthly
  'shop-weekly-free-gift': {
    id: 'shop-weekly-free-gift',
    type: 'weekly',
    category: 'shop',
    labelKey: 'progress.task.shop-weekly-free-gift',
    permanent: true,
    maxCount: 1,
    shopCategory: 'progress.shop.premium-shop',
    shopSubcategory: 'progress.shop.normal',
    shopTab: 'progress.shop.daily-weekly-monthly',
  },
  // Content > Event Shop > Joint Challenge
  'shop-weekly-jc-ticket': {
    id: 'shop-weekly-jc-ticket',
    type: 'weekly',
    category: 'shop',
    labelKey: '',
    permanent: true,
    maxCount: 1,
    shopCategory: 'progress.shop.adventurer-shop',
    shopSubcategory: 'progress.shop.event-shop',
    shopTab: 'progress.shop.joint-challenge',
    shopItemKey: 'Special Recruitment Ticket (Event)',
    shopItemQuantity: 1,
  },
  'shop-weekly-jc-armor-glunite': {
    id: 'shop-weekly-jc-armor-glunite',
    type: 'weekly',
    category: 'shop',
    labelKey: '',
    permanent: true,
    maxCount: 1,
    shopCategory: 'progress.shop.adventurer-shop',
    shopSubcategory: 'progress.shop.event-shop',
    shopTab: 'progress.shop.joint-challenge',
    shopItemKey: 'Armor Glunite',
    shopItemQuantity: 1,
  },
  'shop-weekly-jc-gold': {
    id: 'shop-weekly-jc-gold',
    type: 'weekly',
    category: 'shop',
    labelKey: '',
    permanent: true,
    maxCount: 100,
    shopCategory: 'progress.shop.adventurer-shop',
    shopSubcategory: 'progress.shop.event-shop',
    shopTab: 'progress.shop.joint-challenge',
    shopItemKey: 'Gold',
    shopItemQuantity: 20000,
  },
  'shop-weekly-jc-present': {
    id: 'shop-weekly-jc-present',
    type: 'weekly',
    category: 'shop',
    labelKey: '',
    permanent: true,
    maxCount: 1,
    shopCategory: 'progress.shop.adventurer-shop',
    shopSubcategory: 'progress.shop.event-shop',
    shopTab: 'progress.shop.joint-challenge',
    shopItemKey: 'Legendary Quality Present Chest',
    shopItemQuantity: 10,
  },
  'shop-weekly-jc-gem': {
    id: 'shop-weekly-jc-gem',
    type: 'weekly',
    category: 'shop',
    labelKey: '',
    permanent: true,
    maxCount: 1,
    shopCategory: 'progress.shop.adventurer-shop',
    shopSubcategory: 'progress.shop.event-shop',
    shopTab: 'progress.shop.joint-challenge',
    shopItemKey: 'Stage 5 Random Gem Chest',
    shopItemQuantity: 1,
  },
  // Content > General
  'shop-weekly-general-intermediate-manual': {
    id: 'shop-weekly-general-intermediate-manual',
    type: 'weekly',
    category: 'shop',
    labelKey: '',
    permanent: true,
    maxCount: 1,
    shopCategory: 'progress.shop.premium-shop',
    shopSubcategory: 'progress.shop.general',
    shopItemKey: 'Intermediate Skill Manual',
    shopItemQuantity: 2,
  },
  'shop-weekly-general-basic-manual': {
    id: 'shop-weekly-general-basic-manual',
    type: 'weekly',
    category: 'shop',
    labelKey: '',
    permanent: true,
    maxCount: 1,
    shopCategory: 'progress.shop.premium-shop',
    shopSubcategory: 'progress.shop.general',
    shopItemKey: 'Basic Skill Manual',
    shopItemQuantity: 5,
  },
  // Content > Friendship Point
  'shop-weekly-fp-hero-piece': {
    id: 'shop-weekly-fp-hero-piece',
    type: 'weekly',
    category: 'shop',
    labelKey: '',
    permanent: true,
    maxCount: 1,
    shopCategory: 'progress.shop.adventurer-shop',
    shopSubcategory: 'progress.shop.friendship-point',
    shopItemKey: '3★ Hero Piece Selective Exchange Ticket',
    shopItemQuantity: 1,
  },
  'shop-weekly-fp-upgrade-stone': {
    id: 'shop-weekly-fp-upgrade-stone',
    type: 'weekly',
    category: 'shop',
    labelKey: '',
    permanent: true,
    maxCount: 1,
    shopCategory: 'progress.shop.adventurer-shop',
    shopSubcategory: 'progress.shop.friendship-point',
    shopItemKey: 'Upgrade Stone Selection Chest',
    shopItemQuantity: 1,
  },
  'shop-weekly-fp-upgrade-piece': {
    id: 'shop-weekly-fp-upgrade-piece',
    type: 'weekly',
    category: 'shop',
    labelKey: '',
    permanent: true,
    maxCount: 1,
    shopCategory: 'progress.shop.adventurer-shop',
    shopSubcategory: 'progress.shop.friendship-point',
    shopItemKey: 'Upgrade Stone Piece Selection Chest',
    shopItemQuantity: 1,
  },
  // Content > Arena Shop
  'shop-weekly-arena-basic-manual': {
    id: 'shop-weekly-arena-basic-manual',
    type: 'weekly',
    category: 'shop',
    labelKey: '',
    permanent: true,
    maxCount: 5,
    shopCategory: 'progress.shop.adventurer-shop',
    shopSubcategory: 'progress.shop.arena-shop',
    shopItemKey: 'Basic Skill Manual',
    shopItemQuantity: 1,
  },
  'shop-weekly-arena-inter-manual': {
    id: 'shop-weekly-arena-inter-manual',
    type: 'weekly',
    category: 'shop',
    labelKey: '',
    permanent: true,
    maxCount: 3,
    shopCategory: 'progress.shop.adventurer-shop',
    shopSubcategory: 'progress.shop.arena-shop',
    shopItemKey: 'Intermediate Skill Manual',
    shopItemQuantity: 1,
  },
  'shop-weekly-arena-pro-manual': {
    id: 'shop-weekly-arena-pro-manual',
    type: 'weekly',
    category: 'shop',
    labelKey: '',
    permanent: true,
    maxCount: 2,
    shopCategory: 'progress.shop.adventurer-shop',
    shopSubcategory: 'progress.shop.arena-shop',
    shopItemKey: 'Professional Skill Manual',
    shopItemQuantity: 1,
  },
  // Content > Star Memory
  'shop-weekly-starmem-inter-manual': {
    id: 'shop-weekly-starmem-inter-manual',
    type: 'weekly',
    category: 'shop',
    labelKey: '',
    permanent: true,
    maxCount: 2,
    shopCategory: 'progress.shop.premium-shop',
    shopSubcategory: 'progress.shop.star-memory',
    shopItemKey: 'Intermediate Skill Manual',
    shopItemQuantity: 1,
  },
  'shop-weekly-starmem-pro-manual': {
    id: 'shop-weekly-starmem-pro-manual',
    type: 'weekly',
    category: 'shop',
    labelKey: '',
    permanent: true,
    maxCount: 1,
    shopCategory: 'progress.shop.premium-shop',
    shopSubcategory: 'progress.shop.star-memory',
    shopItemKey: 'Professional Skill Manual',
    shopItemQuantity: 1,
  },
  'shop-weekly-starmem-ticket': {
    id: 'shop-weekly-starmem-ticket',
    type: 'weekly',
    category: 'shop',
    labelKey: '',
    permanent: true,
    maxCount: 1,
    shopCategory: 'progress.shop.premium-shop',
    shopSubcategory: 'progress.shop.star-memory',
    shopItemKey: 'Special Recruitment Ticket',
    shopItemQuantity: 2,
  },
  'shop-weekly-starmem-transistone': {
    id: 'shop-weekly-starmem-transistone',
    type: 'weekly',
    category: 'shop',
    labelKey: '',
    permanent: true,
    maxCount: 4,
    shopCategory: 'progress.shop.premium-shop',
    shopSubcategory: 'progress.shop.star-memory',
    shopItemKey: 'Transistone (Total)',
    shopItemQuantity: 1,
  },
  // Content > Adventure License Shop
  'shop-weekly-al-proof-of-worth': {
    id: 'shop-weekly-al-proof-of-worth',
    type: 'weekly',
    category: 'shop',
    labelKey: '',
    permanent: true,
    icon: 'items/TI_Licence',
    maxCount: 25,
    shopCategory: 'progress.shop.adventurer-shop',
    shopSubcategory: 'progress.shop.adventure-license',
    shopItemKey: 'Proof of Worth',
    shopItemQuantity: 1,
  },
  'shop-weekly-al-gem-chest': {
    id: 'shop-weekly-al-gem-chest',
    type: 'weekly',
    category: 'shop',
    labelKey: '',
    permanent: true,
    icon: 'items/TI_Licence',
    maxCount: 2,
    shopCategory: 'progress.shop.adventurer-shop',
    shopSubcategory: 'progress.shop.adventure-license',
    shopItemKey: 'Stage 5–6 Gem Chest',
    shopItemQuantity: 1,
  },
  // Guild > Guild Shop > Weekly Products
  'shop-weekly-guild-basic-manual': {
    id: 'shop-weekly-guild-basic-manual',
    type: 'weekly',
    category: 'shop',
    labelKey: '',
    permanent: true,
    maxCount: 3,
    shopCategory: 'progress.shop.guild',
    shopSubcategory: 'progress.shop.guild-shop',
    shopTab: 'progress.shop.weekly-products',
    shopItemKey: 'Basic Skill Manual',
    shopItemQuantity: 1,
  },
  'shop-weekly-guild-intermediate-manual': {
    id: 'shop-weekly-guild-intermediate-manual',
    type: 'weekly',
    category: 'shop',
    labelKey: '',
    permanent: true,
    maxCount: 2,
    shopCategory: 'progress.shop.guild',
    shopSubcategory: 'progress.shop.guild-shop',
    shopTab: 'progress.shop.weekly-products',
    shopItemKey: 'Intermediate Skill Manual',
    shopItemQuantity: 1,
  },
  'shop-weekly-guild-professional-manual': {
    id: 'shop-weekly-guild-professional-manual',
    type: 'weekly',
    category: 'shop',
    labelKey: '',
    permanent: true,
    maxCount: 1,
    shopCategory: 'progress.shop.guild',
    shopSubcategory: 'progress.shop.guild-shop',
    shopTab: 'progress.shop.weekly-products',
    shopItemKey: 'Professional Skill Manual',
    shopItemQuantity: 1,
  },
  'shop-weekly-guild-hero-piece': {
    id: 'shop-weekly-guild-hero-piece',
    type: 'weekly',
    category: 'shop',
    labelKey: '',
    permanent: true,
    maxCount: 5,
    shopCategory: 'progress.shop.guild',
    shopSubcategory: 'progress.shop.guild-shop',
    shopTab: 'progress.shop.weekly-products',
    shopItemKey: '[Guild] 3★ Hero Piece Selection Chest',
    shopItemQuantity: 1,
  },
  // Kate's Workshop (Craft)
  'craft-weekly-potentium-armor': {
    id: 'craft-weekly-potentium-armor',
    type: 'weekly',
    category: 'craft',
    labelKey: '',
    permanent: true,
    icon: 'ui/nav/CM_Agit_Crafting',
    maxCount: 2,
    shopCategory: 'progress.craft.kates-workshop',
    shopItemKey: 'Potentium (Armor)',
    shopItemQuantity: 1,
  },
  'craft-weekly-potentium-weapon': {
    id: 'craft-weekly-potentium-weapon',
    type: 'weekly',
    category: 'craft',
    labelKey: '',
    permanent: true,
    icon: 'ui/nav/CM_Agit_Crafting',
    maxCount: 2,
    shopCategory: 'progress.craft.kates-workshop',
    shopItemKey: 'Potentium (Weapon/Accessory)',
    shopItemQuantity: 1,
  },
  'craft-weekly-armor-glunite': {
    id: 'craft-weekly-armor-glunite',
    type: 'weekly',
    category: 'craft',
    labelKey: '',
    permanent: true,
    icon: 'ui/nav/CM_Agit_Crafting',
    maxCount: 2,
    shopCategory: 'progress.craft.kates-workshop',
    shopItemKey: 'Armor Glunite',
    shopItemQuantity: 1,
  },
  'craft-weekly-blue-stardust': {
    id: 'craft-weekly-blue-stardust',
    type: 'weekly',
    category: 'craft',
    labelKey: '',
    permanent: true,
    icon: 'ui/nav/CM_Agit_Crafting',
    maxCount: 4,
    shopCategory: 'progress.craft.kates-workshop',
    shopItemKey: 'Blue Stardust',
    shopItemQuantity: 1,
  },
  'craft-weekly-blue-memory-stone': {
    id: 'craft-weekly-blue-memory-stone',
    type: 'weekly',
    category: 'craft',
    labelKey: '',
    permanent: true,
    icon: 'ui/nav/CM_Agit_Crafting',
    maxCount: 4,
    shopCategory: 'progress.craft.kates-workshop',
    shopItemKey: 'Blue Memory Stone',
    shopItemQuantity: 1,
  },
}

export const MONTHLY_TASK_DEFINITIONS: Record<string, TaskDefinition> = {
  // Regular tasks
  'skyward-tower-100': {
    id: 'skyward-tower-100',
    type: 'monthly',
    category: 'task',
    labelKey: 'progress.task.skyward-tower-100',
    permanent: true,
    maxCount: 1,
  },
  'skyward-tower-hard-40': {
    id: 'skyward-tower-hard-40',
    type: 'monthly',
    category: 'task',
    labelKey: 'progress.task.skyward-tower-hard-40',
    permanent: true,
    maxCount: 1,
  },
  'skyward-tower-vhard-20': {
    id: 'skyward-tower-vhard-20',
    type: 'monthly',
    category: 'task',
    labelKey: 'progress.task.skyward-tower-vhard-20',
    permanent: true,
    maxCount: 4, // 4 phases of 5 floors each
    hasProgressiveUnlock: true,
  },
  // Irregular Extermination
  'irregular-floor-3': {
    id: 'irregular-floor-3',
    type: 'monthly',
    category: 'task',
    labelKey: 'progress.task.irregular-floor-3',
    permanent: true,
    maxCount: 1,
  },
  'irregular-queen': {
    id: 'irregular-queen',
    type: 'monthly',
    category: 'task',
    labelKey: 'progress.task.irregular-queen',
    permanent: true,
    maxCount: 1,
  },
  'irregular-wyvre': {
    id: 'irregular-wyvre',
    type: 'monthly',
    category: 'task',
    labelKey: 'progress.task.irregular-wyvre',
    permanent: true,
    maxCount: 1,
  },
  'irregular-iron-stretcher': {
    id: 'irregular-iron-stretcher',
    type: 'monthly',
    category: 'task',
    labelKey: 'progress.task.irregular-iron-stretcher',
    permanent: true,
    maxCount: 1,
  },
  'irregular-blockbuster': {
    id: 'irregular-blockbuster',
    type: 'monthly',
    category: 'task',
    labelKey: 'progress.task.irregular-blockbuster',
    permanent: true,
    maxCount: 1,
  },
  // Premium Shop > Normal > Daily/Weekly/Monthly
  'shop-monthly-free-gift': {
    id: 'shop-monthly-free-gift',
    type: 'monthly',
    category: 'shop',
    labelKey: 'progress.task.shop-monthly-free-gift',
    permanent: true,
    maxCount: 1,
    shopCategory: 'progress.shop.premium-shop',
    shopSubcategory: 'progress.shop.normal',
    shopTab: 'progress.shop.daily-weekly-monthly',
  },
  // Content > World Boss Shop
  'shop-monthly-worldboss-transistone-total': {
    id: 'shop-monthly-worldboss-transistone-total',
    type: 'monthly',
    category: 'shop',
    labelKey: '',
    permanent: true,
    icon: 'items/TI_Item_World_Boss',
    maxCount: 2,
    shopCategory: 'progress.shop.adventurer-shop',
    shopSubcategory: 'progress.shop.world-boss',
    shopItemKey: 'Transistone (Total)',
    shopItemQuantity: 1,
  },
  'shop-monthly-worldboss-transistone-individual': {
    id: 'shop-monthly-worldboss-transistone-individual',
    type: 'monthly',
    category: 'shop',
    labelKey: '',
    permanent: true,
    icon: 'items/TI_Item_World_Boss',
    maxCount: 2,
    shopCategory: 'progress.shop.adventurer-shop',
    shopSubcategory: 'progress.shop.world-boss',
    shopItemKey: 'Transistone (Individual)',
    shopItemQuantity: 1,
  },
  'shop-monthly-worldboss-gold': {
    id: 'shop-monthly-worldboss-gold',
    type: 'monthly',
    category: 'shop',
    labelKey: '',
    permanent: true,
    icon: 'items/TI_Item_World_Boss',
    maxCount: 100,
    shopCategory: 'progress.shop.adventurer-shop',
    shopSubcategory: 'progress.shop.world-boss',
    shopItemKey: 'Gold',
    shopItemQuantity: 10000,
  },
  // Content > Event Shop > Joint Challenge
  'shop-monthly-jc-refined-glunite': {
    id: 'shop-monthly-jc-refined-glunite',
    type: 'monthly',
    category: 'shop',
    labelKey: '',
    permanent: true,
    maxCount: 1,
    shopCategory: 'progress.shop.adventurer-shop',
    shopSubcategory: 'progress.shop.event-shop',
    shopTab: 'progress.shop.joint-challenge',
    shopItemKey: 'Refined Glunite',
    shopItemQuantity: 1,
  },
  'shop-monthly-jc-transistone-individual': {
    id: 'shop-monthly-jc-transistone-individual',
    type: 'monthly',
    category: 'shop',
    labelKey: '',
    permanent: true,
    maxCount: 1,
    shopCategory: 'progress.shop.adventurer-shop',
    shopSubcategory: 'progress.shop.event-shop',
    shopTab: 'progress.shop.joint-challenge',
    shopItemKey: 'Transistone (Individual)',
    shopItemQuantity: 1,
  },
  'shop-monthly-jc-transistone-total': {
    id: 'shop-monthly-jc-transistone-total',
    type: 'monthly',
    category: 'shop',
    labelKey: '',
    permanent: true,
    maxCount: 1,
    shopCategory: 'progress.shop.adventurer-shop',
    shopSubcategory: 'progress.shop.event-shop',
    shopTab: 'progress.shop.joint-challenge',
    shopItemKey: 'Transistone (Total)',
    shopItemQuantity: 1,
  },
  // Content > Star Memory
  'shop-monthly-starmem-glunite': {
    id: 'shop-monthly-starmem-glunite',
    type: 'monthly',
    category: 'shop',
    labelKey: '',
    permanent: true,
    maxCount: 1,
    shopCategory: 'progress.shop.premium-shop',
    shopSubcategory: 'progress.shop.star-memory',
    shopItemKey: 'Refined Glunite',
    shopItemQuantity: 1,
  },
  'shop-monthly-starmem-transistone-individual': {
    id: 'shop-monthly-starmem-transistone-individual',
    type: 'monthly',
    category: 'shop',
    labelKey: '',
    permanent: true,
    maxCount: 4,
    shopCategory: 'progress.shop.premium-shop',
    shopSubcategory: 'progress.shop.star-memory',
    shopItemKey: 'Transistone (Individual)',
    shopItemQuantity: 1,
  },
  // Content > Survey Hub
  'shop-monthly-survey-basic-manual': {
    id: 'shop-monthly-survey-basic-manual',
    type: 'monthly',
    category: 'shop',
    labelKey: '',
    permanent: true,
    icon: 'items/TI_Item_Research_Point',
    maxCount: 40,
    shopCategory: 'progress.shop.adventurer-shop',
    shopSubcategory: 'progress.shop.survey-hub',
    shopItemKey: 'Basic Skill Manual',
    shopItemQuantity: 1,
  },
  'shop-monthly-survey-intermediate-manual': {
    id: 'shop-monthly-survey-intermediate-manual',
    type: 'monthly',
    category: 'shop',
    labelKey: '',
    permanent: true,
    icon: 'items/TI_Item_Research_Point',
    maxCount: 25,
    shopCategory: 'progress.shop.adventurer-shop',
    shopSubcategory: 'progress.shop.survey-hub',
    shopItemKey: 'Intermediate Skill Manual',
    shopItemQuantity: 1,
  },
  'shop-monthly-survey-professional-manual': {
    id: 'shop-monthly-survey-professional-manual',
    type: 'monthly',
    category: 'shop',
    labelKey: '',
    permanent: true,
    icon: 'items/TI_Item_Research_Point',
    maxCount: 9,
    shopCategory: 'progress.shop.adventurer-shop',
    shopSubcategory: 'progress.shop.survey-hub',
    shopItemKey: 'Professional Skill Manual',
    shopItemQuantity: 1,
  },
  'shop-monthly-survey-talisman': {
    id: 'shop-monthly-survey-talisman',
    type: 'monthly',
    category: 'shop',
    labelKey: '',
    permanent: true,
    icon: 'items/TI_Item_Research_Point',
    maxCount: 1,
    shopCategory: 'progress.shop.adventurer-shop',
    shopSubcategory: 'progress.shop.survey-hub',
    shopItemKey: '6★ Talisman Selection Chest',
    shopItemQuantity: 1,
  },
  'shop-monthly-survey-recruitment-ticket': {
    id: 'shop-monthly-survey-recruitment-ticket',
    type: 'monthly',
    category: 'shop',
    labelKey: '',
    permanent: true,
    icon: 'items/TI_Item_Research_Point',
    maxCount: 30,
    shopCategory: 'progress.shop.adventurer-shop',
    shopSubcategory: 'progress.shop.survey-hub',
    shopItemKey: 'Special Recruitment Ticket (Event)',
    shopItemQuantity: 1,
  },
  'shop-monthly-survey-free-ether': {
    id: 'shop-monthly-survey-free-ether',
    type: 'monthly',
    category: 'shop',
    labelKey: '',
    permanent: true,
    icon: 'items/TI_Item_Research_Point',
    maxCount: 500,
    shopCategory: 'progress.shop.adventurer-shop',
    shopSubcategory: 'progress.shop.survey-hub',
    shopItemKey: 'Free Ether',
    shopItemQuantity: 1,
  },
  'shop-monthly-survey-transistone-individual': {
    id: 'shop-monthly-survey-transistone-individual',
    type: 'monthly',
    category: 'shop',
    labelKey: '',
    permanent: true,
    icon: 'items/TI_Item_Research_Point',
    maxCount: 2,
    shopCategory: 'progress.shop.adventurer-shop',
    shopSubcategory: 'progress.shop.survey-hub',
    shopItemKey: 'Transistone (Individual)',
    shopItemQuantity: 1,
  },
  'shop-monthly-survey-transistone-total': {
    id: 'shop-monthly-survey-transistone-total',
    type: 'monthly',
    category: 'shop',
    labelKey: '',
    permanent: true,
    icon: 'items/TI_Item_Research_Point',
    maxCount: 2,
    shopCategory: 'progress.shop.adventurer-shop',
    shopSubcategory: 'progress.shop.survey-hub',
    shopItemKey: 'Transistone (Total)',
    shopItemQuantity: 1,
  },
  'shop-monthly-survey-glunite': {
    id: 'shop-monthly-survey-glunite',
    type: 'monthly',
    category: 'shop',
    labelKey: '',
    permanent: true,
    icon: 'items/TI_Item_Research_Point',
    maxCount: 5,
    shopCategory: 'progress.shop.adventurer-shop',
    shopSubcategory: 'progress.shop.survey-hub',
    shopItemKey: 'Refined Glunite',
    shopItemQuantity: 1,
  },
  // Kate's Workshop (Craft)
  'craft-monthly-transistone-total': {
    id: 'craft-monthly-transistone-total',
    type: 'monthly',
    category: 'craft',
    labelKey: '',
    permanent: true,
    icon: 'ui/nav/CM_Agit_Crafting',
    maxCount: 3,
    shopCategory: 'progress.craft.kates-workshop',
    shopItemKey: 'Transistone (Total)',
    shopItemQuantity: 1,
  },
  'craft-monthly-transistone-individual': {
    id: 'craft-monthly-transistone-individual',
    type: 'monthly',
    category: 'craft',
    labelKey: '',
    permanent: true,
    icon: 'ui/nav/CM_Agit_Crafting',
    maxCount: 3,
    shopCategory: 'progress.craft.kates-workshop',
    shopItemKey: 'Transistone (Individual)',
    shopItemQuantity: 1,
  },
}

// Helper to get all task IDs
export function getAllDailyTaskIds(): string[] {
  return Object.keys(DAILY_TASK_DEFINITIONS)
}

export function getAllWeeklyTaskIds(): string[] {
  return Object.keys(WEEKLY_TASK_DEFINITIONS)
}

export function getAllMonthlyTaskIds(): string[] {
  return Object.keys(MONTHLY_TASK_DEFINITIONS)
}

// Helper to get only permanent task IDs (auto-enabled by default)
export function getPermanentDailyTaskIds(): string[] {
  return Object.values(DAILY_TASK_DEFINITIONS)
    .filter((def) => def.permanent && def.category !== 'craft' && def.category !== 'shop')
    .map((def) => def.id)
}

export function getPermanentWeeklyTaskIds(): string[] {
  return Object.values(WEEKLY_TASK_DEFINITIONS)
    .filter((def) => def.permanent && def.category !== 'craft' && def.category !== 'shop')
    .map((def) => def.id)
}

export function getPermanentMonthlyTaskIds(): string[] {
  return Object.values(MONTHLY_TASK_DEFINITIONS)
    .filter((def) => def.permanent && def.category !== 'craft' && def.category !== 'shop')
    .map((def) => def.id)
}

// Get default enabled craft task IDs (for new users, but can be disabled)
export function getDefaultCraftTaskIds(): string[] {
  return [
    ...Object.values(DAILY_TASK_DEFINITIONS),
    ...Object.values(WEEKLY_TASK_DEFINITIONS),
    ...Object.values(MONTHLY_TASK_DEFINITIONS),
  ]
    .filter((def) => def.permanent && def.category === 'craft')
    .map((def) => def.id)
}

// Get default enabled shop task IDs (for new users, but can be disabled)
export function getDefaultShopTaskIds(): string[] {
  return [
    ...Object.values(DAILY_TASK_DEFINITIONS),
    ...Object.values(WEEKLY_TASK_DEFINITIONS),
    ...Object.values(MONTHLY_TASK_DEFINITIONS),
  ]
    .filter((def) => def.permanent && def.category === 'shop')
    .map((def) => def.id)
}
