import { existsSync, readFileSync, statSync, writeFileSync, mkdirSync, copyFileSync } from 'fs';
import { join, dirname } from 'path';
import { PATHS } from '../config';
import { writeFileAtomicSync } from '../lib/write-json';

const OUTPUT = join(process.cwd(), 'data', 'character-skins.json');
const STAMP = join(PATHS.generated, '.character-skins-stamp');

// Source tables (in data/admin/json2). Both must exist to (re)generate.
const REQUIRED_INPUTS = ['CostumeTemplet', 'TextCharacter'];

// Skin portraits: `CT_<modelNameID>.png`. Source lives in the extracted datamine;
// dest is the public portrait dir. The matching `.webp` is produced by the
// separate image-conversion step, so we only bring over the PNG here.
const PORTRAIT_SRC_DIR = join(
  PATHS.extractedAssets,
  'assets', 'editor', 'resources', 'sprite', 'at_thumbnailcharacterruntime'
);
const PORTRAIT_DEST_DIR = PATHS.images.characters.portrait;

interface CostumeRow {
  ID: string;
  CharacterID: string;
  ModelNameID: string;
  FusionModelNameID: string;
  CostumeName: string;
  SpriteCostumeIcon: string;
  Sort: string;
  ItemGrade: string;
  ShowList: string;
  CostumePurchaseType: string;
}

interface TextRow {
  ID: string;
  Korean?: string;
  English?: string;
  Japanese?: string;
  China_Simplified?: string;
}

interface Skin {
  id: string;
  modelNameID: string;
  fusionModelNameID?: string;
  name: { en: string; jp: string; kr: string; zh: string };
  icon: string;
  rarity: string;
  source: string;
  showList: boolean;
  sort: number;
}

// ItemGrade -> rarity (same scale as the items extractor)
const RARITY_MAP: Record<string, string> = {
  IG_NORMAL: 'normal',
  IG_MAGIC: 'superior',
  IG_RARE: 'epic',
  IG_UNIQUE: 'legendary',
};

// CostumePurchaseType -> normalized source
const SOURCE_MAP: Record<string, string> = {
  CPT_SHOP: 'shop',
  CPT_SHOP_ASSET_NORMAL: 'shop',
  CPT_EVENT_SHOP: 'event_shop',
  CPT_WORLD_BOSS_SHOP: 'world_boss_shop',
  CPT_BATTLEPASS: 'battlepass',
  NONE: 'none',
};

/**
 * Read the raw game tables and build the character -> skins mapping.
 * Pure transform; callers handle skip/stamp/output. Assumes inputs exist.
 */
export function buildCharacterSkins(): Record<string, Skin[]> {
  const costumes: CostumeRow[] = JSON.parse(
    readFileSync(join(PATHS.adminJson2, 'CostumeTemplet.json'), 'utf-8')
  );
  const textRows: TextRow[] = JSON.parse(
    readFileSync(join(PATHS.adminJson2, 'TextCharacter.json'), 'utf-8')
  );
  const text = new Map(textRows.map(r => [r.ID, r]));

  const byCharacter: Record<string, Skin[]> = {};

  for (const row of costumes) {
    const t = text.get(row.CostumeName);

    const skin: Skin = {
      id: row.ID,
      modelNameID: row.ModelNameID,
      name: {
        en: t?.English ?? '',
        jp: t?.Japanese ?? '',
        kr: t?.Korean ?? '',
        zh: t?.China_Simplified ?? '',
      },
      icon: row.SpriteCostumeIcon,
      rarity: RARITY_MAP[row.ItemGrade] ?? row.ItemGrade.toLowerCase(),
      source: SOURCE_MAP[row.CostumePurchaseType] ?? row.CostumePurchaseType.toLowerCase(),
      showList: row.ShowList === 'True',
      sort: Number(row.Sort) || 0,
    };
    if (row.FusionModelNameID && row.FusionModelNameID !== '0') {
      skin.fusionModelNameID = row.FusionModelNameID;
    }

    (byCharacter[row.CharacterID] ??= []).push(skin);
  }

  // Stable order: by sort, then numeric id, within each character
  for (const skins of Object.values(byCharacter)) {
    skins.sort((a, b) => a.sort - b.sort || Number(a.id) - Number(b.id));
  }

  // Sort the top-level keys by numeric character id for a clean diff
  const sorted: Record<string, Skin[]> = {};
  for (const id of Object.keys(byCharacter).sort((a, b) => Number(a) - Number(b))) {
    sorted[id] = byCharacter[id];
  }
  return sorted;
}

/** Serialize exactly as the committed file (pretty + trailing newline). */
export function writeCharacterSkins(data: Record<string, Skin[]>): void {
  writeFileAtomicSync(OUTPUT, JSON.stringify(data, null, 2) + '\n');
}

/**
 * Bring over the `CT_<modelNameID>.png` portrait for every skin that lacks one.
 * No-op when the datamine source dir is absent (prod path). Idempotent: only
 * copies what's missing on disk. The `.webp` is generated by the image step.
 */
export function copyMissingPortraits(data: Record<string, Skin[]>): {
  copied: number;
  noSource: string[];
} {
  if (!existsSync(PORTRAIT_SRC_DIR)) return { copied: 0, noSource: [] };

  const seen = new Set<string>();
  const noSource: string[] = [];
  let copied = 0;

  for (const skins of Object.values(data)) {
    for (const s of skins) {
      const id = s.modelNameID;
      if (seen.has(id)) continue;
      seen.add(id);

      const dest = join(PORTRAIT_DEST_DIR, `CT_${id}.png`);
      if (existsSync(dest)) continue;

      const src = join(PORTRAIT_SRC_DIR, `CT_${id}.png`);
      if (!existsSync(src)) {
        noSource.push(id);
        continue;
      }

      mkdirSync(PORTRAIT_DEST_DIR, { recursive: true });
      copyFileSync(src, dest);
      copied++;
    }
  }

  return { copied, noSource };
}

function latestInputMtime(): number {
  let latest = 0;
  for (const name of REQUIRED_INPUTS) {
    const p = join(PATHS.adminJson2, `${name}.json`);
    if (!existsSync(p)) return 0;
    const m = statSync(p).mtimeMs;
    if (m > latest) latest = m;
  }
  return latest;
}

export async function run() {
  // Graceful skip on the no-datamine path (prod deploys ship the committed JSON).
  if (!existsSync(PATHS.adminJson2)) {
    return existsSync(OUTPUT) ? 'skipped (no json2, using existing)' : 'skipped (no json2)';
  }

  const latest = latestInputMtime();
  if (latest === 0) {
    return existsSync(OUTPUT) ? 'skipped (missing inputs, using existing)' : 'skipped (missing inputs)';
  }

  const upToDate =
    existsSync(STAMP) &&
    existsSync(OUTPUT) &&
    Number(readFileSync(STAMP, 'utf-8').trim()) >= latest;

  const data = buildCharacterSkins();

  // Reconcile portraits on every run (cheap, idempotent): catches skins added
  // before this step existed, even when the JSON itself is already up to date.
  const portraits = copyMissingPortraits(data);
  const portraitMsg = portraits.copied ? `, ${portraits.copied} portrait(s) copied` : '';

  // Stamp guard: skip the JSON rewrite unless an input is newer than last build.
  if (upToDate) {
    return `up to date${portraitMsg}`;
  }

  writeCharacterSkins(data);
  mkdirSync(dirname(STAMP), { recursive: true });
  writeFileSync(STAMP, String(latest), 'utf-8');

  const totalSkins = Object.values(data).reduce((n, s) => n + s.length, 0);
  return `${Object.keys(data).length} characters / ${totalSkins} skins${portraitMsg}`;
}
