import { readdirSync, writeFileSync } from 'fs';
import { join, basename } from 'path';

const EVENTS_DIR = join(
  process.cwd(),
  'src/app/[lang]/tools/_contents/event/events',
);
const OUTPUT = join(EVENTS_DIR, 'index.ts');
const SKIP = new Set(['index.ts', 'config.ts']);

export async function run(): Promise<string> {
  const files = readdirSync(EVENTS_DIR)
    .filter(f => f.endsWith('.tsx') && !SKIP.has(f))
    .sort();

  if (files.length === 0) {
    writeFileSync(
      OUTPUT,
      `/* AUTO-GENERATED — do not edit */\nimport type { EventDef } from '../types';\nimport type { EventStatus } from '../types';\n\nexport type EventWithStatus = EventDef & { status: EventStatus };\nexport const EVENTS: EventWithStatus[] = [];\n`,
    );
    return '0 events';
  }

  const imports: string[] = [];
  const names: string[] = [];

  for (const file of files) {
    const slug = basename(file, '.tsx');
    const ident = 'E_' + slug.replace(/-/g, '_');
    imports.push(`import ${ident} from './${slug}';`);
    names.push(ident);
  }

  const output = `/* AUTO-GENERATED by pipeline — do not edit */
import type { EventDef } from '../types';
import type { EventStatus } from '../types';
import EVENT_STATUS from './config';
${imports.join('\n')}

export type EventWithStatus = EventDef & { status: EventStatus };

const ALL: EventDef[] = [${names.join(', ')}];

export const EVENTS: EventWithStatus[] = ALL.map(e => ({
  ...e,
  status: (EVENT_STATUS[e.meta.slug] ?? 'hidden') as EventStatus,
}));
`;

  writeFileSync(OUTPUT, output);
  return `${files.length} event(s)`;
}
