import { readFile, writeFile } from 'fs/promises';
import { join } from 'path';
import { existsSync } from 'fs';
import { PATHS } from '../config';

const TOWER_DIR = join(process.cwd(), 'data', 'tower');

const BOSS_TYPES = new Set(['CT_BOSS_MONSTER', 'CT_AREA_BOSS_MONSTER', 'CT_SEASON_BOSS_MONSTER']);

type Row = Record<string, string>;

interface TowerConfig {
  name: string;
  mode: string;
  idPrefix: string | null;
}

const TOWERS: TowerConfig[] = [
  { name: 'normal', mode: 'DM_TOWER', idPrefix: null },
  { name: 'fire', mode: 'DM_TOWER_ELEMENT', idPrefix: '40202' },
  { name: 'water', mode: 'DM_TOWER_ELEMENT', idPrefix: '40212' },
  { name: 'earth', mode: 'DM_TOWER_ELEMENT', idPrefix: '40222' },
  { name: 'light', mode: 'DM_TOWER_ELEMENT', idPrefix: '40232' },
  { name: 'dark', mode: 'DM_TOWER_ELEMENT', idPrefix: '40242' },
  { name: 'hard', mode: 'DM_TOWER_HARD', idPrefix: '40102' },
];

// Fields generated by the pipeline (will be overwritten); others are preserved
const GENERATED_FIELDS = new Set(['floor', 'boss_id', 'minions']);

function buildSpawnIndex(spawns: Row[]) {
  const index = new Map<string, Row[]>();
  for (const row of spawns) {
    const groupId = row.GroupID ?? '';
    if (!groupId) continue;
    if (!index.has(groupId)) index.set(groupId, []);
    index.get(groupId)!.push(row);
  }
  return index;
}

function extractFloorMonsters(
  floorRow: Row,
  spawnIdx: Map<string, Row[]>,
  monsterIdx: Map<string, Row>,
): { bossId: string | null; minions: string[] } {
  const allMonsters: { id: string; type: string }[] = [];

  const DUNGEON_SPAWN_FIELDS = [
    'SpawnID_Pos0', 'SpawnID_Pos1', 'SpawnID_Pos2',
  ];
  const SPAWN_MONSTER_SLOTS = ['ID0', 'ID1', 'ID2', 'ID3'];

  for (const pos of DUNGEON_SPAWN_FIELDS) {
    const val = floorRow[pos] ?? '';
    if (!val || val === '0' || /^(true|false)$/i.test(val)) continue;
    for (const groupId of val.split(',').map(s => s.trim())) {
      const spawns = spawnIdx.get(groupId);
      if (!spawns) continue;
      for (const spawn of spawns) {
        for (const slot of SPAWN_MONSTER_SLOTS) {
          const mid = spawn[slot] ?? '';
          if (!mid || mid === '0') continue;
          const monster = monsterIdx.get(mid);
          if (monster) allMonsters.push({ id: mid, type: monster.Type ?? '' });
        }
      }
    }
  }

  let bossId: string | null = null;
  const minions: string[] = [];
  for (const { id, type } of allMonsters) {
    if (BOSS_TYPES.has(type)) {
      bossId = id;
    } else if (!minions.includes(id)) {
      minions.push(id);
    }
  }
  return { bossId, minions };
}

async function readTemplet(name: string): Promise<Row[]> {
  const raw = await readFile(join(PATHS.adminJson2, `${name}.json`), 'utf-8');
  return JSON.parse(raw);
}

interface FloorEntry {
  floor: number;
  boss_id: string;
  minions?: string[];
  [key: string]: unknown;
}

async function generateTower(
  tower: TowerConfig,
  dungeons: Row[],
  spawnIdx: Map<string, Row>,
  monsterIdx: Map<string, Row>,
): Promise<{ floors: FloorEntry[]; missing: string[] }> {
  // Load existing data to preserve curated fields
  const existingPath = join(TOWER_DIR, `${tower.name}.json`);
  const existingFloors = new Map<number, FloorEntry>();
  if (existsSync(existingPath)) {
    const raw = await readFile(existingPath, 'utf-8');
    const data = JSON.parse(raw);
    for (const fl of data.floors ?? []) existingFloors.set(fl.floor, fl);
  }

  const towerFloors = dungeons
    .filter(r =>
      r.DungeonMode === tower.mode &&
      (tower.idPrefix === null || (r.ID ?? '').startsWith(tower.idPrefix)),
    )
    .sort((a, b) => parseInt(a.ID ?? '0') - parseInt(b.ID ?? '0'));

  const floors: FloorEntry[] = [];
  const allIds = new Set<string>();

  for (let i = 0; i < towerFloors.length; i++) {
    const floorNum = i + 1;
    const { bossId, minions } = extractFloorMonsters(towerFloors[i], spawnIdx, monsterIdx);

    const entry: FloorEntry = { floor: floorNum, boss_id: bossId ?? '' };
    if (minions.length > 0) entry.minions = minions;

    // Preserve manually-curated fields
    const existing = existingFloors.get(floorNum);
    if (existing) {
      for (const [key, value] of Object.entries(existing)) {
        if (!GENERATED_FIELDS.has(key)) entry[key] = value;
      }
    }

    if (bossId) allIds.add(bossId);
    for (const m of minions) allIds.add(m);

    floors.push(entry);
  }

  // Check for missing boss files
  const missing: string[] = [];
  for (const id of allIds) {
    if (!existsSync(join(PATHS.bosses, `${id}.json`))) missing.push(id);
  }

  return { floors, missing };
}

export async function run() {
  if (!existsSync(PATHS.adminJson2)) {
    return 'skipped (no admin json)';
  }

  const [dungeonT, spawnT, monsterT] = await Promise.all([
    readTemplet('DungeonTemplet'),
    readTemplet('DungeonSpawnTemplet'),
    readTemplet('MonsterTemplet'),
  ]);

  const monsterIdx = new Map(monsterT.map(r => [r.ID, r]));
  const spawnIdx = buildSpawnIndex(spawnT);

  let totalFloors = 0;
  let totalMissing = 0;

  const allMissing: { id: string; tower: string; floor: number }[] = [];

  for (const tower of TOWERS) {
    const { floors, missing } = await generateTower(tower, dungeonT, spawnIdx, monsterIdx);

    // Write tower JSON
    const outputPath = join(TOWER_DIR, `${tower.name}.json`);
    await writeFile(outputPath, JSON.stringify({ floors }, null, 2));

    // Track missing for report
    for (const id of missing) {
      const floor = floors.find(f => f.boss_id === id || f.minions?.includes(id));
      allMissing.push({ id, tower: tower.name, floor: floor?.floor ?? 0 });
    }

    totalFloors += floors.length;
    totalMissing += missing.length;
  }

  // Write missing monsters file
  const missingPath = join(TOWER_DIR, 'missing-monsters.json');
  // Deduplicate by id (keep first occurrence with role info)
  const seen = new Set<string>();
  const dedupMissing: { id: string; role: string; tower: string; floor: number }[] = [];
  for (const m of allMissing) {
    if (seen.has(m.id)) continue;
    seen.add(m.id);
    // Determine role
    const towerPath = join(TOWER_DIR, `${m.tower}.json`);
    const towerData = JSON.parse(await readFile(towerPath, 'utf-8'));
    const fl = (towerData.floors as FloorEntry[]).find(f => f.floor === m.floor);
    const role = fl?.boss_id === m.id ? 'boss' : 'minion';
    dedupMissing.push({ id: m.id, role, tower: m.tower, floor: m.floor });
  }
  await writeFile(missingPath, JSON.stringify(dedupMissing, null, 2));

  return `${TOWERS.length} towers, ${totalFloors} floors, ${totalMissing} missing`;
}
