import { join } from 'path'
import { mkdir } from 'fs/promises'
import { dirname } from 'path'
import { PATHS } from '../../config'
import { writeFileAtomic } from '../../lib/write-json'

/**
 * Schema version of the bake outputs. Bump when the on-disk shape changes
 * so client-side caches (browser HTTP cache + service worker) can invalidate.
 * The reader compares this against the manifest's `_v` and refuses stale
 * detail files.
 */
export const SCHEMA_VERSION = '1'

/**
 * Damage calculator runtime artifacts live under `public/` so the browser can
 * fetch them directly with no API hop. Same files are read server-side via
 * `fs` for SSR / SEO, and client-side via `fetch('/damage-calc/...')`.
 *
 * Outputs are gitignored — regenerated by every pipeline run.
 */
export const OUTPUT_DIR = join(process.cwd(), 'public', 'damage-calc')

/** Minified JSON write — these files are runtime artifacts, not diff'd. */
export async function writeJsonMin(relPath: string, data: unknown): Promise<void> {
  const abs = join(OUTPUT_DIR, relPath)
  await mkdir(dirname(abs), { recursive: true })
  await writeFileAtomic(abs, JSON.stringify(data))
}

/** Convenience for builders: paths to commonly-read inputs. */
export const INPUTS = {
  json2: PATHS.adminJson2,
  characters: PATHS.characters,
  generated: PATHS.generated,
} as const
